name: TaskScheduler Unit Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  UnitTests_Linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev pkg-config
          
      - name: Build and install Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo cmake --build . --target all
          sudo cp lib/*.a /usr/lib || sudo cp *.a /usr/lib
          
      - name: Create CMakeLists.txt
        run: |
          cat > CMakeLists.txt << 'EOF'
          cmake_minimum_required(VERSION 3.10)
          project(TaskSchedulerTests VERSION 1.0.0)

          set(CMAKE_CXX_STANDARD 14)
          set(CMAKE_CXX_STANDARD_REQUIRED ON)

          # Find required packages
          find_package(PkgConfig REQUIRED)
          find_package(Threads REQUIRED)

          # Include directories
          include_directories(${CMAKE_SOURCE_DIR}/src)
          include_directories(${CMAKE_SOURCE_DIR}/tests)

          # Gather source files
          file(GLOB TASKSCHEDULER_SOURCES 
              "${CMAKE_SOURCE_DIR}/src/*.cpp"
              "${CMAKE_SOURCE_DIR}/src/*.c"
          )

          file(GLOB TEST_SOURCES 
              "${CMAKE_SOURCE_DIR}/tests/*.cpp"
          )

          # Check if we have test files
          list(LENGTH TEST_SOURCES TEST_COUNT)
          if(TEST_COUNT EQUAL 0)
              message(FATAL_ERROR "No test files found in tests/ directory")
          endif()

          # Create the test executable
          add_executable(taskscheduler_tests
              ${TEST_SOURCES}
              ${TASKSCHEDULER_SOURCES}
          )

          # Link libraries
          target_link_libraries(taskscheduler_tests
              gtest
              gtest_main
              pthread
          )

          # Compiler definitions for Arduino compatibility
          target_compile_definitions(taskscheduler_tests PRIVATE
              ARDUINO=200
              _TASK_MICRO_RES=0
              _TASK_STD_FUNCTION=0
              _TASK_TIMECRITICAL=0
              _TASK_STATUS_REQUEST=0
              _TASK_WDT_IDS=0
              _TASK_LTS_POINTER=0
              _TASK_PRIORITY=0
              _TASK_TIMEOUT=0
              _TASK_OO_CALLBACKS=0
              _TASK_DEFINE_MILLIS=0
              _TASK_INLINE=0
              _TASK_THREAD_SAFE=0
              _TASK_SLEEP_ON_IDLE_RUN=0
          )

          # Compiler flags
          target_compile_options(taskscheduler_tests PRIVATE
              -Wall
              -Wextra
              -O2
          )

          # Enable testing
          enable_testing()
          add_test(NAME TaskSchedulerUnitTests COMMAND taskscheduler_tests)
          EOF
          
      - name: Create simplified test file
        run: |
          mkdir -p tests
          cat > tests/simple_test.cpp << 'EOF'
          #include <gtest/gtest.h>
          #include <chrono>
          #include <thread>

          // Mock Arduino functions
          unsigned long millis() {
              static auto start = std::chrono::steady_clock::now();
              auto now = std::chrono::steady_clock::now();
              return std::chrono::duration_cast<std::chrono::milliseconds>(now - start).count();
          }

          void delay(unsigned long ms) {
              std::this_thread::sleep_for(std::chrono::milliseconds(ms));
          }

          void yield() {
              std::this_thread::yield();
          }

          // Include TaskScheduler
          #include "TaskScheduler.h"

          // Simple test that just verifies compilation
          TEST(TaskSchedulerTest, BasicCompilation) {
              Scheduler ts;
              EXPECT_TRUE(true);
          }

          TEST(TaskSchedulerTest, SchedulerExecution) {
              Scheduler ts;
              
              // Run scheduler a few times - should not crash
              for (int i = 0; i < 10; i++) {
                  ts.execute();
                  delay(1);
              }
              
              EXPECT_TRUE(true);
          }
          EOF
          
      - name: Build tests
        run: |
          cmake .
          make -j$(nproc)
          
      - name: Run unit tests
        run: |
          ./taskscheduler_tests
