name: TaskScheduler Unit Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  UnitTests_Linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev pkg-config
          
      - name: Build and install Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo cmake --build . --target all
          sudo cp lib/*.a /usr/lib || sudo cp *.a /usr/lib
          
      - name: Build tests
        run: |
          cmake .
          make -j$(nproc)
          
      - name: Run unit tests
        run: |
          ./taskscheduler_tests --gtest_output=xml:test_results.xml
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test_results.xml